### ISSUE TITLE
Cloud security (add new user) Phase II

### ISSUE THREAD

**Issue by sshi100** [commitdev/zero-aws-eks-stack#109]
Along with [Could security - add new member](https://app.zenhub.com/workspaces/commit-zero-5da8decc7046a60001c6db44/issues/commitdev/zero/223), we completed DevOps/Admin side with kind of best experience. However, we need to further figure out how to improve new member side of experience with quick client setup and resource accessibility to both AWS and K8S.

**Comment by sshi100** [comment]
Workflow(draft):
DevOps: send user a temporary password (required to reset when first login)
Member: run script "setup-user-access.sh", to help setup client configuration and verify resource access

Tasks:
- [ ] TF: create user temporary password and display to DevOps
- [ ] Script: setup-user-access.sh, including AWS credentials, K8s context and resource access sanity test report
- [ ] README

**Comment by sshi100** [comment]
Per discussion with @bmonkman , as TF creation of password (even temporary password) needs to deal with `keybase` and consider of small team of password distribution practice, we would create another ticket for later handling. For now, we just have an Operator to manually create temporary password and pass to the team in whatever way that they feel confident and convenient.

**Comment by sshi100** [comment]
For requirement #3, a new ticket is created https://github.com/commitdev/zero-aws-eks-stack/issues/115

**Comment by bmonkman** [comment]
Can you add some documentation about how to use the aws cli to create temporary passwords? Maybe a one-liner or something they could run..

**Comment by sshi100** [comment]
Enhancements:
- added user profile setup script for Admin, which does auto-detect "new" users and create temporary passwords etc.

**Comment by sshi100** [comment]
Flow:
1. ops-person: add new users into the users array in `shared/main.tf`, then do `make apply`;
2. ops-person: run `scripts/setup-user-password.sh` to create their passwords
3. ops-person: grant git access and pass password to new users
4. new-user: checkout git code, and run `scripts/setup-user-access` and run locally
