### ISSUE TITLE
Enable AWS Cloudtrail by default

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-aws-eks-stack#113]
To enable some baseline auditing capabilities we should make sure cloudtrail is enabled. There is a Cloudpossee module for it but we can probably make do with just the default aws provider resource here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail
We don't need to get too fancy with it, and ideally we can stay within the free usage tier.

**Comment by sshi100** [comment]
AC:
- [ ] Add cloudtrail module
- [ ] Call from zero-eks side by default
