### ISSUE TITLE
Investigate using NAT instances instead of NAT gateways to save cost

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-aws-eks-stack#166]
It could be cheaper to use NAT instances if we use small instance classes, though we would potentially introduce issues for people who need a lot of outbound traffic from their cluster. Could be something we prompt for during setup - let them choose..

**Comment by sshi100** [comment]
Specs:
- NAT Instance used for Staging environment only, while keep NAT gateway for Production
- One NAT instance per AZ

**Comment by sshi100** [comment]
Spec:
- Enable S3 VPC endpoint to save cost for S3 access

**Comment by sshi100** [comment]
Put NAT instance as part of VPC module, with a controller `enable_nat_gateway`. When it is set as false, create NAT instance instead of NAT gateway.

**Comment by sshi100** [comment]
Allow user to define own NAT instance type (default: t3.nano)
