### ISSUE TITLE
Add support for Elasticache Redis

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-aws-eks-stack#167]
Add terraform to enable support of Elasticache Redis.
As usual, let's try to use a well-supported existing TF module as the basis for this.

If this is done after memcached, the code should be reused. If it's done before it should take into account that we also want to support memcached.

**Comment by bmonkman** [comment]
Related to #168

**Comment by sshi100** [comment]
After investigation, I prefer use [this](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster), which supports both Memcache and Redis.

**Comment by bmonkman** [comment]
The `aws_elasticache_cluster` resource will make a cluster for memcached but it only supports a single instance group for redis. For Redis you should use a replication group. I would suggest using the cloudposse modules instead of just the provider.

**Comment by sshi100** [comment]
Decision:
combine both as a single module with selection of redis or memcache:
- https://registry.terraform.io/modules/cloudposse/elasticache-memcached/aws/latest
- https://registry.terraform.io/modules/cloudposse/elasticache-redis/aws/latest

**Comment by sshi100** [comment]
Support both Redis and Memcached, ready for go backend to use.

PRs:
- Module: https://github.com/commitdev/terraform-aws-zero/pull/32
- Infrastructure: https://github.com/commitdev/zero-aws-eks-stack/pull/177
- Backend(go): https://github.com/commitdev/zero-deployable-backend/pull/55
