### ISSUE TITLE
Add support for Elasticache Memcached

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-aws-eks-stack#168]
Add terraform to enable support of Elasticache Memcached.

As usual, let's try to use a well-supported existing TF module as the basis for this.

If this is done after redis, the code should be reused. If it's done before it should take into account that we also want to support redis.

**Comment by bmonkman** [comment]
Related to #167

**Comment by sshi100** [comment]
Implemented with [#167](https://app.zenhub.com/workspaces/commit-zero-5da8decc7046a60001c6db44/issues/commitdev/zero-aws-eks-stack/167)
