### ISSUE TITLE
Remove t2 instances as default type

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-aws-eks-stack#233]
The default staging environment has a t2 instance type as an option, which should be removed. T2 instances don't support IP prefixes which means these instances would have much lower IP limits.
https://github.com/commitdev/zero-aws-eks-stack/blob/87f27a9c47ff47648c22af2292b545608545cb77/templates/terraform/environments/stage/main.tf#L79

**Comment by deven96** [comment]
Does this simply mean? @bmonkman 
```tf
    instance_types = ["t3.medium", "t3.large"]
```
