### ISSUE TITLE
Error: "name_prefix" cannot be longer than 32 characters, name is limited to 64

### ISSUE THREAD

**Issue by trevoro** [commitdev/zero-aws-eks-stack#25]
When running the `make apply` command I ran into this error

```
Error: "name_prefix" cannot be longer than 32 characters, name is limited to 64

  on .terraform/modules/production.eks.eks/terraform-aws-eks-10.0.0/cluster.tf line 98, in resource "aws_iam_role" "cluster":
  98: resource "aws_iam_role" "cluster" {
```

The name of my project was just "trevoro-test2".
We should probably look at shortening up some of the names for our own things, and then enforcing the length of the fields we let users define.

**Comment by hudhaifahz** [comment]
Came across this myself as well.

How Hashicorp handles it:
https://github.com/hashicorp/terraform/issues/13186
https://github.com/hashicorp/terraform/issues/12947
