### ISSUE TITLE
terraform tries to recreate ci-user twice for different environments

### ISSUE THREAD

**Issue by thdaraujo** [commitdev/zero-aws-eks-stack#49]
`apply-secrets` will not work when you already have an existing environment set up because terraform tries to create the `ci-user` again.

For `apply-env`, terraform also tries to recreate these policies with the same name and it fails:
`eks_list_and_describe_policy` `ci_user_list_and_describe_policy` (https://github.com/commitdev/zero-aws-eks-stack/blob/master/templates/terraform/modules/environment/iam.tf)

**Comment by bmonkman** [comment]
I already fixed the secrets part of this in this commit: https://github.com/commitdev/zero-aws-eks-stack/commit/d03b86ad6726d887e0179433403cd79eca1ac128

**Comment by bmonkman** [comment]
But yes, you're right, those policies need env-specific names. Thanks!
