### ISSUE TITLE
Add tests for generated terraform

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero-aws-eks-stack#88]
Add github action to run zero create with a predefined zero-project.yml, generate code, then run `terraform validate` to detect any syntax errors.
We'll need to make sure to keep the values in the config file up to date or tests will start failing. These tests should be run on all branches before allowing a merge to main.

We could either run validate ourselves like this: 
https://github.com/commitdev/terraform-aws-zero/blob/main/.github/workflows/terraform.yml

 or use Github's super linter:
https://github.com/github/super-linter

**Comment by dtoki** [comment]
to get the latest binary: https://api.github.com/repos/commitdev/zero/releases/latest
